### ISSUE TITLE
Bug: AUTOINCREMENT is being forced on incompatible column type of primary key

### ISSUE THREAD

**Issue by realjjaveweb** [dflourusso/expo-sqlite-orm#50]
SQLite does not support AUTOINCREMENT on text columns, but `_createTableColumns()` code is always pushing `NOT NULL PRIMARY KEY AUTOINCREMENT` on primary key, of ANY type.

Settings autoincrement should have option to be disabled (I would keep turned on by default).
Or automatically removed, when the column type is `TEXT`.

**Comment by orhangazi** [comment]
I am getting an error while: 
``` lang-js
     const usersTable = await Users.createTable()
     console.log("Users created successfully", usersTable)
```
"AUTOINCREMENT is only allowed on an INTEGER PRIMARY KEY (code 1 SQLITE_ERROR)". I am already setting it in the Users.js:

``` lang-js
static get columnMapping() {
	return {
		id: { type: types.TEXT, primary_key: true, AUTOINCREMENT: false }, // For while only supports id as primary key
		userName: { type: types.TEXT },
		userSurname: { type: types.TEXT },
		telNo: { type: types.TEXT, not_null: true },
		deviceId: { type: types.TEXT },
		statusMessage: { type: types.TEXT },
		isValidated: { type: types.INTEGER, default: 0, not_null: true },
		isAdmin: { type: types.INTEGER, not_null: false, default: 0 },//if isAdmin=1 phone owner, it will authentication.
		profilePicture: { type: types.TEXT },
		expoPushToken: { type: types.TEXT },
		createdDate: { type: types.INTEGER, not_null: true, default: () =>Date.now() }
	}
}
```

**Comment by dflourusso** [comment]
I'm currently working on the V2 for this project. There are many breaking changes, migrations and typescript support.
If want try, [here is the branch](https://github.com/dflourusso/expo-sqlite-orm/tree/feature/v2), and currently it's on the [alpha 5](https://www.npmjs.com/package/expo-sqlite-orm/v/2.0.0-alpha-5) version.

This bug is simple to fix, I will try to fix it in the next week

Thank you for using this project and helping to make it better

**Comment by dflourusso** [comment]
Hello, V2 is live now. In V2 we have [migrations](https://github.com/dflourusso/expo-sqlite-orm#execute-the-migrations), so you can create the tables and columns as you want.
